#!/usr/bin/env python3
"""Generate port/linux/src/tag_layouts.h: the pointer fields of every tag
struct of Xbox Halo CE cache files (from Invader's definitions via
tagdefs.py), for the runtime relocation walk in tag_relocate.c. Structs that
hold no pointers anywhere below them are left out.

usage: gen_tag_layouts.py <output.h>"""
import sys
from tagdefs import Layout

KINDS = {'block': '_tag_field_block', 'data': '_tag_field_data', 'reference': '_tag_field_reference',
         'pointer': '_tag_field_pointer', 'struct': '_tag_field_struct'}

layout = Layout()
groups = layout.groups()
memo = {}


def has_pointers(name):
    if name not in memo:
        memo[name] = False
        memo[name] = any(kind != 'struct' or has_pointers(child) for _, kind, child in layout.fields[name])
    return memo[name]


# every struct reachable from a group root that holds pointers
order, index = [], {}


def visit(name):
    if name in index or not has_pointers(name):
        return
    index[name] = len(order)
    order.append(name)
    for _, kind, child in layout.fields[name]:
        if child:
            visit(child)


for fourcc, root in sorted(groups.items()):
    visit(root)
visit('ScenarioStructureBSP')

lines = ['/* tag_layouts.h: generated by tools/gen_tag_layouts.py from Invader\'s tag definitions; do not edit */', '',
         'static const struct tag_layout_field tag_layout_fields[] = {']
starts = []
count = 0
for name in order:
    starts.append(count)
    for offset, kind, child in layout.fields[name]:
        if kind in ('block', 'struct') and child and not has_pointers(child):
            if kind == 'struct':
                continue
            child_index, child_size = 0xFFFF, layout.sizes[child]
        elif child:
            child_index, child_size = index[child], layout.sizes[child]
        else:
            child_index, child_size = 0xFFFF, 0
        lines.append(f'\t{{ {offset}, {KINDS[kind]}, {child_index}, {child_size} }}, /* {name} */')
        count += 1
lines.append('};')
lines.append('')
lines.append('static const struct tag_layout_struct tag_layout_structs[] = {')
for i, name in enumerate(order):
    end = starts[i + 1] if i + 1 < len(starts) else count
    lines.append(f'\t{{ {starts[i]}, {end - starts[i]} }}, /* {i} {name} */')
lines.append('};')
lines.append('')
lines.append('static const struct tag_layout_group tag_layout_groups[] = {')
for fourcc, root in sorted(groups.items()):
    root_index = index.get(root, 0xFFFF)
    lines.append(f"\t{{ 0x{fourcc:08X}UL, {root_index} }}, /* {fourcc.to_bytes(4, 'big').decode()} {root} */")
lines.append('};')
lines.append('')
lines.append(f'#define TAG_LAYOUT_STRUCTURE_BSP {index["ScenarioStructureBSP"]}')
open(sys.argv[1], 'w').write('\n'.join(lines) + '\n')
print(f'{len(order)} structs, {count} fields, {len(groups)} groups')
